name: "Test, Lint & Deploy"
on: [push, pull_request]
env:
  DIRENV_WARN_TIMEOUT: 5m
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: nix flake check
      - name: Install direnv with Nix
        uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
      - name: Lint
        run: deno task lint
      - name: Yaml lint
        run: yamlfmt -lint .
      - name: Format
        run: deno task format
      - name: Test
        run: deno task test:coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: cov_profile/html/
  npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo TAG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
      - name: Build
        run: nix develop --command deno task build ${{steps.get_tag_version.outputs.TAG_VERSION}}
      - name: Archive generated npm package
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: npm/
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./npm
        run: nix develop --keep NODE_AUTH_TOKEN --command npm publish
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Install direnv with Nix
        uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
      - name: Generate docs
        run: deno task docs
      - name: Archive docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/
      - uses: actions/upload-pages-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          path: ./docs
      - name: Deploy to GitHub Pages
        if: startsWith(github.ref, 'refs/tags/')
        id: deployment
        uses: actions/deploy-pages@v2
